### ISSUE TITLE
Update for SonarQube 6.7

### ISSUE THREAD

**Issue by braykov** [ciricihq/gitlab-sonar-scanner#15]
The LTS release is now 6.7

I get the following warnings:

* `WARN: The use of the issues mode (sonar.analysis.mode=issues) is deprecated. This mode will be dropped in the future.`
* `WARN: Ability to set quality profile from command line using 'sonar.profile' is deprecated and will be dropped in a future SonarQube version.`
* `WARN: The use of "sonar.branch" is deprecated and replaced by "sonar.branch.name". See https://redirect.sonarsource.com/doc/branches.html.`

The last one is most important for me as `sonar.branch` is now incompatible with `sonar.branch.name` and I cannot use the new branch feature by SonarQube.

**Comment by elboletaire** [comment]
We're still using version 6.2, so this is not a priority for us ATM.

PR are welcome btw, so feel free to make one with the required changes and we'll take care of merging it and creating a specific docker tag for it.

**Comment by elboletaire** [comment]
Done in 3.0.0.

Note that the `WARN: The use of the issues mode...` is still there because we're still not sure how to proceed (apparently, [the sonar-gitlab-plugin creator either](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/132)).
