### ISSUE TITLE
Create proper docker tags per SonarQube version

### ISSUE THREAD

**Issue by elboletaire** [ciricihq/gitlab-sonar-scanner#29]
Before accepting PR from greater versions, we should fix the tags we're defining for docker hub, or, at least, add tags for each sonarqube version we have plugins for.

Right now, based on user comments and issues, and based on our experience, we should, at least, create these two tags:

- 6.2 (our currently used version, and used by many others. It should be compatible until version 6.6
- 6.7 (see #15)

**Comment by gtrias** [comment]
@elboletaire Should we match our gitlab-sonar-scanner tags to the [ones](https://github.com/SonarSource/sonarqube/releases) of sonarqube?

**Comment by elboletaire** [comment]
I'm still not really sure

**Comment by elboletaire** [comment]
So, we finally decided to continue with our custom tags, but they will be really close to the versions used by sonar-gitlab-plugin.

Due to the latest gitlab-sonarqube (and gitlab itself) updates, we'll use the version 3.0.0 for Sonarqube >= 7, Gitlab >= 11 and sonar-gitlab-plugin >= 3.0.0
