### ISSUE TITLE
When token is used?

### ISSUE THREAD

**Issue by phouverneyuff** [ciricihq/gitlab-sonar-scanner#8]
Take a look the code bellow in sonar-scanner-run.sh:
```
#!/bin/sh

URL=$SONAR_URL
SONAR_TOKEN=$SONAR_TOKEN

if [ -z "$SONAR_PROJECT_KEY" ]; then
  echo "Undefined \"projectKey\"" && exit 1
else
  COMMAND="sonar-scanner -Dsonar.host.url=\"$URL\" -Dsonar.projectKey=\"$SONAR_PROJECT_KEY\""
....
```

I can't see SONAR_TOKEN being used. Can I login in my private sonar using token and put the report inside it?

**Comment by gtrias** [comment]
Thanks for the pull request. 
We have the permission for anyone to execute analysis since we're hosting our sonar server in internal network. So we aren't using SONAR_TOKEN.
Can you confirm if now is working for you and close the issue?

**Comment by phouverneyuff** [comment]
I'll test

**Comment by phouverneyuff** [comment]
Worked! Thanks for accept!

**Comment by elboletaire** [comment]
You're welcome 😃
